import { Karla } from "next/font/google";
import "./globals.css";

const karla = Karla({
	subsets: ["latin"],
	weight: ["200", "400", "600", "800"],
});

export const metadata = {
	title: "Empakt Software: Staffing services, Job Search and Placements",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={karla.className} suppressHydrationWarning>
				{children}
			</body>
		</html>
	);
}
